class_name RiverPath
extends Resource
## Stores a single river's path as a polyline with per-point width.
## Generated by RiverGenerator, consumed by RiverBody for mesh building.

## World-space polyline points (Vector3) from source to mouth.
## Y values are terrain height at each point.
@export var points: PackedVector3Array = PackedVector3Array()

## Per-point river half-width in world units. Same length as points.
## Width tapers from narrow upstream to wide downstream.
@export var widths: PackedFloat32Array = PackedFloat32Array()

## Unique identifier for this river (e.g. "river_0").
@export var id: String = ""

## Index used for debug coloring (0-based).
@export var color_index: int = 0


func get_length() -> float:
	## Returns the total polyline length in world units.
	var total: float = 0.0
	for i in range(1, points.size()):
		total += points[i - 1].distance_to(points[i])
	return total


func get_point_count() -> int:
	return points.size()
